blank_issues_enabled: false
contact_links:
  - name: "Python OpenAPI Contributing: Reporting Bugs"
    url: https://openapi-core.readthedocs.io/en/latest/contributing.html#reporting-bugs
    about: Read guidance about Reporting Bugs in the repository.
